name: Daily Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Add your steps here
      - name: Print Time
        run: |
          echo "The workflow ran at $(date)."
